project:
  type: website
  output-dir: docs

website:
  title: "Scott Wagner"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - photography.qmd
      - href: resume.pdf
        text: Resume

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

