project:
  type: website
  output-dir: docs

website:
  title: "Scott Wagner"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - href: photography.qmd
        text: Photography
      - href: resume.pdf
        text: Resume

format:
  html:
    theme: 
    - minty 
    - styles.scss
    mainfont: Oswald
    toc: true
    page-layout: full

editor: visual

