---
title: "About Me"
page-layout: full
toc: false
---

A short list of what I love to do.

+---------------+:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ## Water Polo | From a young age, I tried many different sports, including baseball, basketball, and tennis, but didn't find a meaningful connection with any of them. It was then that I found water polo, a unique mix of endurance, skill, and teamwork. I was instantly hooked, begging my mom to play on the local club team. This was over 10 years ago, since then I have played for my local high school, community college, and now the UCSB club team. |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ## Traveling  | Fortunately, I have been able to travel to many incredible places, taking in their landscapes and learning about their unique cultures. My personal favorite locations have been Italy, Switzerland, Germany, and Hawaii. I hope to keep exploring in the near future and learn more about environmental opportunities in unfamiliar places.                                                                                                     |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|               | \                                                                                                                                                                                                                                                                                                                                                                                                                                                |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ## Surfing    |                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
